name: Release Tauri App

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
      name: Build and Release
      runs-on: ${{ matrix.platform }}
      
      permissions:
        contents: write

      strategy:
        fail-fast: false
        matrix:
          platform: [macos-latest, ubuntu-22_04, windows-latest]
      
      steps:
        - uses: actions/checkout@v4

        - name: Instalacja Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Instalacja Rust toolchain
          uses: dtolnay/rust-toolchain@stable

        - name: Build i publikacja z Tauri Action
          uses: tauri-apps/tauri-action@v0.5.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tagName: app-v__VERSION__
            releaseName: 'bookoteka v__VERSION__'
            releaseBody: 'Automatyczna wersja aplikacji bookoteka.'
            releaseDraft: true
            prerelease: false
